In [ ]:
# pip install tensorflow==1.0.0
# pip install keras==2.0.2

In [1]:

import numpy as np
from keras.utils import np_utils
import tensorflow as tf
# Using TensorFlow 1.0.0; use tf.python_io in later versions
tf.python.control_flow_ops = tf

# Set random seed
np.random.seed(42)

# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')

# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation

# Building the model
xor = Sequential()

# Add required layers
# xor.add()
xor.add(Dense(8, input_dim=X.shape[1]))
xor.add(Activation('tanh'))


xor.add(Dense(1))
# Add a sigmoid activation layer
xor.add(Activation('sigmoid'))

# Specify loss as "binary_crossentropy", optimizer as "adam",
# and add the accuracy metric
# xor.compile()
xor.compile(loss="binary_crossentropy", optimizer="adam", metrics = ["accuracy"])


# Uncomment this line to print the model architecture
xor.summary()

# Fitting the model
history = xor.fit(X, y, nb_epoch=1000, verbose=0)

# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))


Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 24        
_________________________________________________________________
activation_1 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 33.0
Trainable params: 33.0
Non-trainable params: 0.0
_________________________________________________________________


/home/chris/anaconda2/lib/python2.7/site-packages/keras/models.py:826: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


4/4 [==============================] - 0s
('\nAccuracy: ', 1.0)

Predictions:
4/4 [==============================] - 0s
[[ 0.06285986]
 [ 0.86676705]
 [ 0.911731  ]
 [ 0.11276747]]


In [2]:
# simple model with a single hidden layer. 

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Activation


# X has shape (num_rows, num_cols), where the training data are stored
# as row vectors
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)

# y must have an output vector for each input vector
y = np.array([[0], [0], [0], [1]], dtype=np.float32)


In [3]:

# Create the Sequential model
model = Sequential()

print (X.shape[0])

print (X.shape[1])

# 1st Layer - Add an input layer of 32 nodes with the same input shape as the training samples in X
model.add(Dense(32, input_dim=X.shape[1]))

# Add a softmax activation layer
model.add(Activation('softmax'))

# this is equicalent to 
# model.add(Dense(32, input_dim=X.shape[1], activation="softmax"))


# 2nd Layer - Add a fully connected output layer
model.add(Dense(1))

# Add a sigmoid activation layer
model.add(Activation('sigmoid'))




4
2


In [4]:
# Once we have our model built, we need to compile it before it can be run. 
# Compiling the Keras model calls the backend (tensorflow, theano, etc.) 
# and binds the optimizer, loss function, and other parameters required 
# before the model can be run on any input data. 
# We'll specify the loss function to be categorical_crossentropy 
# which can be used when there are only two classes, 
# and specify adam as the optimizer 
# (which is a reasonable default when speed is a priority). 
# And finally, we can specify what metrics we want to evaluate the model with. 
# Here we'll use accuracy.
model.compile(loss="binary_crossentropy", optimizer="adam", metrics = ["accuracy"])

#model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics = ["accuracy"])

In [5]:
# see the resulting model architecture with the following command
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 32)                96        
_________________________________________________________________
activation_3 (Activation)    (None, 32)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33        
_________________________________________________________________
activation_4 (Activation)    (None, 1)                 0         
Total params: 129.0
Trainable params: 129.0
Non-trainable params: 0.0
_________________________________________________________________


In [6]:
print (y)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]


In [7]:
model.fit(X, y, nb_epoch=10, verbose=0)

In [8]:
score = model.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(model.predict_proba(X))



4/4 [==============================] - 0s
('\nAccuracy: ', 0.25)

Predictions:
4/4 [==============================] - 0s
[[ 0.51118052]
 [ 0.51391613]
 [ 0.50766087]
 [ 0.5103094 ]]
